@startuml

class ObjectScope {
- parent: ObjectScopeProtocol
- storageFactory: InstanceStorage
+ init(storageFactory, parent)
}

interface ObjectScopeProtocol {
+ makeStorage() -> InstanceStorage
}

ObjectScopeProtocol <|.. ObjectScope
ObjectScope ..> InstanceStorage : using


interface InstanceStorage {
- instance: Any?
+ graphResolutionCompleted()
+ instance(GraphIdentifier) -> Any
+ setInstance(Any, GraphIdentifier)
}

class GraphStorage {

}

class WeakStorage {

}

class CompositeStorage {
- components: [InstanceStorage]
}

InstanceStorage <|.. GraphStorage
InstanceStorage <|.. WeakStorage
InstanceStorage <|.. CompositeStorage



interface Assembly {
+ assemble(Container)
+ loaded(Resolver)
}

note left of Assembly: 仅提供接口，未实现具体类，由外界实现具体类

class Assembler {
- container: Container
+ resolver: Resolver

+ init(assemblies: [Assembly], parent: Assembly, defaultObjectScope: ObjectScope, behavior: [Behavior])
+ apply(assemblies: [Assembly])
- run(assemblies: [Assembly]) 
}

Assembler ..> Assembly : using
Assembler "1"-->"1" Container

interface ServiceEntryProtocol {
+ objectScope: ObjectScopeProtocol
+ storage: InstanceStorage
+ factory: Any
+ initCompleted: Any?
+ serviceType: Any.Type
}

class ServiceEnty {
+ init(serviceType: Service.Type, argumentsType: Any.Type, factory: Any, objectScope: ObjectScope)
}

ServiceEntryProtocol <|.. ServiceEnty
ServiceEnty "1"-->"1" InstanceStorage

interface Behavior {
+ container(container: Container, didRegisterType: Type, entry: ServiceEnty, name: String?)
}
note top of Behavior: 仅提供接口，未实现具体类，由外界实现具体类传入


interface ServiceKeyOption {
+ isEqualTo(another: ServiceKeyOption)->Bool
+ hash(into: inout Hasher)
}
note top of ServiceKeyOption: 仅提供接口，未实现具体类，可由外界自定义实现

class ServiceKey {
+ serviceType: Any
+ argumentsType: Any
+ name: String?
+ option: ServiceKeyOption?

+ init(serviceType, argumentsType, name, option)
+ hash(into hasher: inout Hasher)
}

ServiceKey ..> ServiceKeyOption : using
note left of ServiceKey::"hash(into hasher: inout Hasher)"
    该方法使用到了自定义的ServiceKeyOption
end note

interface Resolver {
+ resolve(serviceType: Service.Type) -> Service?
+ resolve(serviceType: Service.Type, name: String?, argument: Arg1) -> Service?
}

class Container {
- services: [ServiceKey: ServiceEntryProtocol]
- parent: Container?
- resolutionDepth: Int 
- defaultObjectScope: ObjectScope
- synchronized: Bool
- currentObjectGraph: GraphIdentifier?
- lock: RecursiveLock
- behaviors: [Behavior]

+ init(parent: Container, defualtObjectScope: ObjectScope, behaviors: [Behavior], registeringClosure: (Container)->Void)
- init(parent: Container, debugHelper: DebugHelper, defaultObjectScope: ObjectScope, synchronized: Bool)
+ removeAll() // remove all serivces
+ resetObjectScope(objectScope: ObjectScopeProtocol)
+ register(serviceType: Service.Type, factory: (Arguments)->Any, name: String?, option: SerivceKeyOption)
+ synchronize() -> Resolver
+ addBehavior(behavior: Behavior)
+ hasAnyRegistration(serviceType: Service.Type, name: String?)
}

Container <|.. Resolver

Container "1"-->"n" ServiceKey
Container "1"-->"n" ServiceEntryProtocol
Container "1"-->"1" ObjectScope
Container "1"-->"1" GraphIdentifier
Container "1"-->"n" Behavior

Container ..> ServiceKeyOption : using


@enduml